#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xFFF8BD96
yabai -m config normal_window_border_color   0xFF1E1E2E
yabai -m config insert_feedback_color        ff8474
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
#yabai -m config mouse_modifier               cmd
#yabai -m config mouse_action1                move
#yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
#yabai -m config external_bar                 all:30:00

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5 
yabai -m config bottom_padding               5 
yabai -m config left_padding                 5 
yabai -m config right_padding                5 
yabai -m config window_gap                   5 

# Renaming the spaces
yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V
yabai -m space 6 --label VI

# Turn off management for certain apps
yabai -m rule --add app="^FaceTime$" manage=off border=off
yabai -m rule --add app="^Préférences système$" manage=off border=off
yabai -m rule --add app="QuickTime Player" manage=off border=on layer=below
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="Notion" opacity=0.97 
yabai -m rule --add app="Numi" manage=off border=off 
yabai -m rule --add app="^CleanShot X$" border=off manage=off
yabai -m rule --add app="1Password$" border=off manage=off

## IDEA Jetbrains
#######
yabai -m rule --add app="^JetBrains Toolbox$" border=off manage=off opacity=0.8
yabai -m rule --add app="^PhpStorm" display=2 opacity=0.97

# Floating PHPStorm subwindows
yabai -m rule --add app="^PhpStorm$" manage=off
yabai -m rule --add app="^PhpStorm$" title="( – )"  manage=on

echo "yabai configuration loaded.."
